### ISSUE TITLE
Exception in Verse.AI.ThinkNode_Priority.TryIssueJobPackage: System.NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by janaxis** [AndroidQuazar/VanillaExpandedFramework#55] opened 2022-07-28 00:20 UTC
Hi, 
I keep getting an error when pawns attack zombies. Not sure if issue is with MVCF or Zombieland. 
Issue posted to both =)

hugslib log: https://gist.github.com/HugsLibRecordKeeper/d8c77bf1d62c6bab1b142a08da7d2f48

![error](https://user-images.githubusercontent.com/94777181/181394061-9a53795a-7625-483e-91fb-20880b592d7f.PNG)
[error.txt](https://github.com/AndroidQuazar/VanillaExpandedFramework/files/9204328/error.txt)

**Comment by II-ELIF-II** [comment] 2022-10-23 16:56
I have the same issue I think
[Player.txt](https://github.com/AndroidQuazar/VanillaExpandedFramework/files/9847064/Player.txt)

**Comment by legodude17** [comment] 2022-10-24 09:12
Duplicate of Vanilla-Expanded/VanillaExpandedFramework#1.

**Closed by legodude17** 2022-10-24 09:12 UTC
